# Generated by Django 3.2.6 on 2021-08-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu_payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpurchase',
            name='administrative_fee_base',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='attempts',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='bank_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='bank_referenced_name',
            field=models.CharField(default='bank', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='billing_address',
            field=models.CharField(default='address', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='billing_city',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='billing_country',
            field=models.CharField(default='Bogota', max_length=10),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='cc_holder',
            field=models.CharField(default='buyer card', max_length=100),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='cc_number',
            field=models.CharField(default='000', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='currency',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='customer_number',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='date',
            field=models.DateTimeField(default='2015-05-27 12:04:37'),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='description',
            field=models.CharField(default='desc', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='email_buyer',
            field=models.CharField(default='buyer@buyer.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='error_code_bank',
            field=models.CharField(default='err', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='error_message_bank',
            field=models.CharField(default='err', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='exchange_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='franchise',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='installments_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=40),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='merchant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='nickname_buyer',
            field=models.CharField(default='nickname', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='nickname_seller',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='payment_method',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='payment_method_id',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='payment_method_name',
            field=models.CharField(default='card', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='payment_method_type',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='payment_request_state',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='phone',
            field=models.CharField(default='1234567890', max_length=20),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='pse_bank',
            field=models.CharField(default='bank', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='reference_pol',
            field=models.CharField(default='ref', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='reference_sale',
            field=models.DateTimeField(default='2015-05-27 12:04:37'),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='response_message_pol',
            field=models.CharField(default='message', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='shipping_address',
            field=models.CharField(default='addr', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='shipping_city',
            field=models.CharField(default='city', max_length=55),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='shipping_country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='sign',
            field=models.CharField(default='000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='state_pol',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='transaction_date',
            field=models.DateTimeField(default='2015-05-27 12:04:37'),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='transaction_id',
            field=models.CharField(default='00000', max_length=40),
        ),
    ]
