# Generated by Django 3.2.6 on 2021-08-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu_payment', '0002_auto_20210812_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpurchase',
            name='additional_value',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='administrative_fee_base',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='attempts',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='bank_referenced_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='billing_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='billing_city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='billing_country',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='cc_holder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='cc_number',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='currency',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='customer_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='email_buyer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='error_code_bank',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='error_message_bank',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='exchange_rate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='franchise',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='installments_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='ip',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='merchant_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='nickname_buyer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='nickname_seller',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='payment_method',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='payment_method_id',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='payment_method_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='payment_method_type',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='payment_request_state',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='pse_bank',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='reference_pol',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='reference_sale',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='response_code_pol',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='response_message_pol',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='shipping_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=55),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='shipping_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='sign',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='state_pol',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='test',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='transaction_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
