# Generated by Django 3.2.6 on 2021-08-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu_payment', '0003_auto_20210813_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpurchase',
            name='customer_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='logpurchase',
            name='reference_sale',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
