# Generated by Django 3.2.6 on 2021-08-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payu_payment', '0004_auto_20210813_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logpurchase',
            name='risk',
            field=models.FloatField(blank=True),
        ),
    ]
