from django.db import models

class LogPurchase(models.Model):

    response_code_pol = models.CharField(max_length=255)
    phone = models.CharField(max_length=20, default="1234567890")
    additional_value = models.FloatField(default=0.00)
    test = models.SmallIntegerField(default=1)
    transaction_date = models.DateTimeField(default="2015-05-27 12:04:37")
    cc_number=models.CharField(max_length=255, default="000")
    cc_holder=models.CharField(max_length=100, default="buyer card")
    error_code_bank = models.CharField(max_length=255, default="err")
    billing_country = models.CharField(max_length=10, default="Bogota")
    bank_referenced_name = models.CharField(max_length=255, default="bank")
    description = models.CharField(max_length=255, default="desc")
    value = models.FloatField(default=0.00)
    payment_method_type = models.SmallIntegerField(default=1)
    email_buyer = models.CharField(max_length=100, default="buyer@buyer.com")
    response_message_pol = models.CharField(max_length=255, default="message")
    error_message_bank = models.CharField(max_length=255, default="err")
    shipping_city = models.CharField(max_length=55, default="city")
    transaction_id = models.CharField(max_length=40, default="00000")
    sign = models.CharField(max_length=255, default="000000")
    tax = models.FloatField(default=0.00)
    payment_method = models.SmallIntegerField(default=1)
    billing_address = models.CharField(max_length=255, default="address")
    payment_method_name = models.CharField(max_length=255, default="card")
    pse_bank=models.CharField(max_length=255, default="bank")
    state_pol= models.SmallIntegerField(default=1)
    date= models.DateTimeField(default="2015-05-27 12:04:37")
    nickname_buyer= models.CharField(max_length=255, default="nickname")
    reference_pol= models.CharField(max_length=255, default="ref")
    currency= models.CharField(max_length=10, default="USD")
    risk=models.FloatField(default=0.00)
    shipping_address=models.CharField(max_length=255, default="addr")
    bank_id=models.SmallIntegerField(default=0)
    payment_request_state=models.CharField(max_length=32, default="")
    customer_number=models.IntegerField(default="")
    administrative_fee_base=models.FloatField(default=0)
    attempts=models.IntegerField(default=1)
    merchant_id=models.IntegerField(default=0)
    exchange_rate=models.FloatField(default=0)
    shipping_country=models.CharField(max_length=50, default="")
    installments_number=models.IntegerField(default=0)
    franchise=models.CharField(max_length=50, default="")
    payment_method_id=models.SmallIntegerField(default=0)
    nickname_seller = models.CharField(max_length=200, default="")
    ip = models.CharField(max_length=40,default="127.0.0.1")
    billing_city=models.CharField(max_length=40,default="")
    reference_sale=models.DateTimeField(default="2015-05-27 12:04:37")

    def __str__(self):
        return self.description