from django.db import models

class LogPurchase(models.Model):

    response_code_pol = models.CharField(max_length=255, blank=True, null=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    additional_value = models.FloatField(blank=True, null=True)
    test = models.SmallIntegerField(blank=True, null=True)
    transaction_date = models.DateTimeField(blank=True, null=True)
    cc_number=models.CharField(max_length=255, blank=True, null=True)
    cc_holder=models.CharField(max_length=100, blank=True, null=True)
    error_code_bank = models.CharField(max_length=255, blank=True, null=True)
    billing_country = models.CharField(max_length=10, blank=True, null=True)
    bank_referenced_name = models.CharField(max_length=255, blank=True, null=True)
    description = models.CharField(max_length=255, blank=True, null=True)
    value = models.FloatField(default=0.00, null=True)
    payment_method_type = models.SmallIntegerField(blank=True, null=True)
    email_buyer = models.CharField(max_length=100, blank=True, null=True)
    response_message_pol = models.CharField(max_length=255, blank=True, null=True)
    error_message_bank = models.CharField(max_length=255, blank=True, null=True)
    shipping_city = models.CharField(max_length=55, blank=True, null=True)
    transaction_id = models.CharField(max_length=40, blank=True, null=True)
    sign = models.CharField(max_length=255, blank=True, null=True)
    tax = models.FloatField(default=0.00, null=True)
    payment_method = models.SmallIntegerField(blank=True, null=True)
    billing_address = models.CharField(max_length=255, blank=True, null=True)
    payment_method_name = models.CharField(max_length=255, blank=True, null=True)
    pse_bank=models.CharField(max_length=255, blank=True, null=True)
    state_pol= models.SmallIntegerField(blank=True, null=True)
    date= models.DateTimeField(blank=True, null=True)
    nickname_buyer= models.CharField(max_length=255, blank=True, null=True)
    reference_pol= models.CharField(max_length=255, blank=True, null=True)
    currency= models.CharField(max_length=10, blank=True, null=True)
    risk=models.FloatField(blank=True, null=True)
    shipping_address=models.CharField(max_length=255, blank=True, null=True)
    bank_id=models.SmallIntegerField(default=0, null=True)
    payment_request_state=models.CharField(max_length=32, blank=True, null=True)
    customer_number=models.IntegerField(blank=True, null=True)
    administrative_fee_base=models.FloatField(blank=True, null=True)
    attempts=models.IntegerField(blank=True, null=True)
    merchant_id=models.IntegerField(blank=True, null=True)
    exchange_rate=models.FloatField(blank=True, null=True)
    shipping_country=models.CharField(max_length=50, blank=True, null=True)
    installments_number=models.IntegerField(blank=True, null=True)
    franchise=models.CharField(max_length=50, blank=True, null=True)
    payment_method_id=models.SmallIntegerField(blank=True, null=True)
    nickname_seller = models.CharField(max_length=200, blank=True, null=True)
    ip = models.CharField(max_length=40,blank=True, null=True)
    billing_city=models.CharField(max_length=40, blank=True, null=True)
    reference_sale=models.CharField(max_length=255 ,blank=True, null=True)

    def __str__(self):
        return self.description